#travis config
language: node_js
node_js: 
   - "14.1.0"
notifications:
  slack: alpheiosproject:9WEA6UNyLr3U0bWIJctp1rqS
before_install:
- export COVERALLS_SERVICE_NAME=travis-pro
- export COVERALLS_REPO_TOKEN=jfAzjkVkTQmBT279oSBs2SH7Ag2QKIfV4

