name: QA incr Build
on: 
  push:
    branches-ignore: 
      - 'master'
  
jobs:

  build:
    runs-on: ubuntu-latest
    needs: [test_components_1, test_components_2, test_components_4, test_components_5, test_others]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
        
    - name: prepare for build
      run: npm run set-node-build-deps && npm run bootstrap

    - name: update env
      run: bash scripts/update_env.sh ${{secrets.DETECT_LANG_API}}

    - name: build
      id: run_build
      run: npm run github-build

    - name: commit
      uses: EndBug/add-and-commit@v4
      with:
        message: "Commit files for build ${{ steps.run_build.outputs.buildName }}"
        add: "lerna.json packages/*/package*.json packages/components/dist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

    - name: revert package.json
      run: git checkout -- package.json && git checkout -- package-lock.json
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.run_build.outputs.buildName }}
        release_name: Release ${{ steps.run_build.outputs.buildName }}
        draft: false
        prerelease: true
        
     

